insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 1,'1395 Jigror Park','67242','Wekviwik','Ohio','Philippines')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 2,'216 Zunnij Grove','16795','Wosilleg','Colorado','Bhutan')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 3,'1016 Capfad View','59016','Ucaedaut','Missouri','Liechtenstein')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 4,'214 Decde River','19120','Uddako','Colorado','Bhutan')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 5,'1050 Bivo Way','50051','Canvorac','Montana','Macedonia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 6,'1734 Judbi Grove','88281','Igulahep','Utah','Syria')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 7,'1143 Joraf Way','54266','Peprafome','New Hampshire','Mexico')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 8,'287 Kemdol Street','19335','Ohruzi','Delaware','Burkina Faso')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 9,'1302 Odeter Circle','67913','Zudsova','North Carolina','Norfolk Island')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 10,'1563 Lisoh Square','70348','Ceksohuje','Rhode Island','Slovenia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 11,'842 Duod Lane','43191','Ladudnu','Massachusetts','Iran')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 12,'1624 Nowuf Plaza','82466','Gipwufpus','South Dakota','Sri Lanka')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 13,'1325 Kagu Loop','61311','Dedguza','North Carolina','Norway')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 14,'310 Feffo Grove','19122','Odgave','Delaware','Cameroon')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 15,'1888 Derwo Park','95026','Pahlosgi','West Virginia','Ukraine')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 16,'1500 Wehovu Boulevard','78723','Aresueba','Pennsylvania','Saudi Arabia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 17,'984 Zamum Drive','41719','Gookpaf','Missouri','Lebanon')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 18,'1497 Dune Parkway','71190','Gawnebuh','Pennsylvania','Saudi Arabia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 19,'1836 Repi Terrace','93520','Lihpiwid','Virginia','Turkmenistan')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 20,'1805 Razup Extension','93516','Lidzuppa','Virginia','Trinidad & Tobago')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 21,'1477 Kulmen Junction','77394','Zewekse','Oregon','Samoa')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 22,'191 Ibca View','03804','Lunaor','California','Belize')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 23,'569 Baaci Place','21005','Faromo','Indiana','Equatorial Guinea')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 24,'999 Tohhij Pass','46672','Vojogkiw','Missouri','Liberia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 25,'736 Tuvo Road','31690','Goborofu','Louisiana','Guadeloupe')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 26,'1153 Foga Turnpike','51161','Fapgasun','New Hampshire','Micronesia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 27,'1764 Uswuz Trail','81978','Fuswuzzub','Utah','Tanzania')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 28,'1818 Hivwe Point','99258','Oginojrip','Virginia','Tristan da Cunha')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 29,'1541 Gugu Heights','71193','Gazgusu','Rhode Island','Singapore')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 30,'1898 Zede Point','93730','Jojdekak','West Virginia','United Kingdom')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 31,'299 Ralcul Place','16514','Vipiul','Delaware','Cambodia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 32,'1018 Turuhu Court','56696','Towezedup','Missouri','Liechtenstein')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 33,'1307 Omjo Highway','63951','Lumjoda','North Carolina','North Korea')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 34,'630 Riggi Park','39542','Injari','Iowa','France')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 35,'1596 Sice Trail','74552','Mincewap','South Carolina','South Georgia & South Sandwich Islands')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 36,'197 Fodin River','02175','Gasamzit','California','Benin')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 37,'1579 Gegi Square','72121','Haggijap','South Carolina','Somalia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 38,'1668 Kuve Park','84383','Netvesa','Tennessee','St. Martin')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 39,'1882 Lapa Boulevard','91303','Febpahu','Washington','Uganda')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 40,'645 Zevvat Pass','37738','Zoisdom','Kansas','French Polynesia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 41,'1380 Nabe Terrace','62414','Jifbeaga','Ohio','Paraguay')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 42,'717 Kaot Ridge','31302','Gejuwij','Louisiana','Greenland')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 43,'1654 Tawuc View','89609','Upajuctuj','Tennessee','St. Lucia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 44,'599 Ehgad Road','21837','Fuzefo','Iowa','Falkland Islands')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 45,'1798 Fajju View','87113','Zacleunu','Vermont','Tonga')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 46,'1198 Pave Extension','50502','Dicveed','New Jersey','Morocco')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 47,'1341 Ispav Mill','61976','Duspaviw','North Dakota','Pakistan')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 48,'110 Haam Grove','03202','Kejuhib','Arizona','Ascension Island')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 49,'1317 Iliat Glen','66845','Vulmutma','North Carolina','Northern Mariana Islands')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 50,'303 Dogo Road','11163','Dakartov','Delaware','Cambodia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 51,'191 Wipir Pike','00745','Borivon','California','Belize')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 52,'923 Iwage Parkway','46891','Tugefpe','Minnesota','Kazakhstan')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 53,'1605 Joopo Avenue','84265','Mepopoju','South Carolina','South Korea')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 54,'718 Gojawu Trail','39273','Ofkotiwu','Louisiana','Greenland')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 55,'1008 Afigoh Path','57714','Atarajip','Missouri','Libya')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 56,'1052 Benom Terrace','51027','Fagnomezi','Montana','Macedonia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 57,'1902 Jevak Lane','99238','Ihelokbe','West Virginia','United Kingdom')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 58,'1128 Darhow Trail','59006','Ucatetilo','Nevada','Mauritius')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 59,'1050 Dupid Extension','51195','Fawpidba','Montana','Macedonia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 60,'1754 Como Manor','84061','Narmouc','Utah','Tajikistan')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 61,'1648 Iguni Drive','87828','Wugfinsi','South Dakota','St. Kitts & Nevis')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 62,'141 Pepal Lane','02529','Jiumne','Arkansas','Bahamas')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 63,'265 Pukvoh Point','17583','Zimopjof','Connecticut','Brunei')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 64,'1088 Vegub Plaza','50625','Cofgubgok','Nebraska','Mali')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 65,'843 Rucwi Point','45580','Sicarwit','Massachusetts','Iran')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 66,'1026 Agijit Manor','56725','Sogzeknew','Montana','Lithuania')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 67,'848 Loolu Pass','42368','Heewirar','Massachusetts','Iran')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 68,'1492 Tupwov Path','77696','Wowvossul','Pennsylvania','São Tomé and Príncipe')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 69,'1086 Hidge Highway','58251','Egikeki','Nebraska','Mali')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 70,'1516 Liow Boulevard','71344','Delowci','Pennsylvania','Serbia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 71,'807 Vesa Point','42633','Jomiwu','Maryland','Hong Kong SAR China')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 72,'1936 Wupik Plaza','94785','Motpikdoh','Wisconsin','Vanuatu')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 73,'1776 Dajsip Terrace','87013','Zadpitu','Vermont','Timor-Leste')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 74,'1381 Soof Avenue','63570','Mitofpe','Ohio','Paraguay')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 75,'1737 Aruzus Plaza','86779','Vorwowvec','Utah','Syria')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 76,'1222 Ufeco Manor','66923','Vufgamil','New Mexico','Namibia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 77,'1311 Uneehi Loop','65963','Sunuvni','North Carolina','North Korea')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 78,'1896 Hahin River','94215','Pedhinaba','West Virginia','United Arab Emirates')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 79,'232 Zunago Street','15786','Rototwu','Colorado','Bosnia & Herzegovina')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 80,'452 Joluk Way','20269','Ceujuuh','Hawaii','Costa Rica')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 81,'1697 Goltu View','86174','Varcouve','Texas','Suriname')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 82,'1862 Lupuwu Junction','96386','Vetsuwkop','Washington','U.S. Outlying Islands')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 83,'1921 Reduz Turnpike','91539','Fihduzris','West Virginia','Uruguay')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 84,'857 Pubsav Square','49490','Ulcunit','Massachusetts','Ireland')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 85,'1008 Lullip Place','58384','Ejuojtom','Missouri','Libya')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 86,'226 Abaudu Center','17800','Wucuduc','Colorado','Bosnia & Herzegovina')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 87,'1688 Kettuj Loop','88338','Ijeopumo','Texas','Sudan')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 88,'204 Junib Circle','04387','Nealidi','Colorado','Bermuda')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 89,'1564 Viobu Way','71659','Fonoburez','Rhode Island','Slovenia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 90,'469 Igfa Parkway','21920','Fucare','Hawaii','Croatia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 91,'440 Omuse River','25959','Suodozu','Hawaii','Cook Islands')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 92,'101 Luwmo Heights','08389','Ejigihoc','Arizona','Aruba')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 93,'312 Pice Ridge','10451','Cigafhec','Delaware','Cameroon')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 94,'76 Zuufa Grove','04796','Movufhe','Alaska','Antigua & Barbuda')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 95,'211 Agmo Circle','10722','Bojidis','Colorado','Bhutan')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 96,'672 Fopav Trail','39166','Odvatije','Kentucky','Gambia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 97,'31 Jibe Ridge','01241','Degawu','Alabama','Algeria')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 98,'723 Lojet Junction','34376','Netegkir','Louisiana','Grenada')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 99,'1095 Ukve Trail','51940','Fukveura','Nebraska','Malta')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 100,'1054 Viipo Boulevard','52658','Gomipova','Montana','Madagascar')
